stages:
  - install_deps
  - build
  - deploy

cache:
  key: '$CI_BUILD_REF'
  untracked: true
  paths:
    - node_modules/
    - dist/

# 安装依赖
install_dev:
  stage: install_deps
  only:
    - develop
  tags:
    - ip-test
  script:
    - npm install

install_prod:
  stage: install_deps
  only:
    - master
  tags:
    - ip-prod
  script:
    - npm install

# 编译
build_dev:
  stage: build
  only:
    - develop
  tags:
    - ip-test
  script:
    - npm run build:staging

build_prod:
  stage: build
  only:
    - master
  tags:
    - ip-prod
  script:
    - npm run build

# 部署
deploy_dev:
  stage: deploy
  only:
    - develop
  tags:
    - ip-test
  script:
    - rm -rf /data/www/front_page/*
    - cp -rf dist/* /data/www/front_page/

deploy_prod:
  stage: deploy
  only:
    - master
  tags:
    - ip-prod
  script:
    - rm -rf /data/www/front_page/*
    - cp -rf dist/* /data/www/front_page/
